name: segmentation_module
_target_: project.models.segmentation_module.SegmentationModule

model: 
  _target_: project.models.components.unet.UNet
  in_channels: ${in_channels}
  out_channels: 1
  first_layer_out_channels: 32
  mask_true_threshold: 0.5

learning_rate: 1e-3