name: segmentation_module
_target_: project.lightning_modules.segmentation_module.SegmentationModule

model: 
  _target_: project.models.unet.UNet
  in_channels: 1
  out_channels: 1
  first_layer_out_channels: 32

# optim:
#   _target_: torch.optim.Adam
#   lr: 1e-3