hydra: 
  run:
    # Configure output dir of each experiment programmatically from the arguments
    # Example "outputs/classifier/baseline/2021-03-10-141516"
    dir: "outputs/${model.name}/${experiment}/${now:%Y-%m-%d_%H%M%S}"

# Global configurations shared between different modules
experiment: "baseline"

# Path to dataset
dataset_path: "dataset"
images_path: "${dataset_path}/images"
masks_path: "${dataset_path}/masks"

# Path to model checkpoint
checkpoint_path: "checkpoint-acc_0.52.ckpt"

# Image channel settings
image_channel: -1  # -1 - all channels
in_channels: 3

# Composing nested config with default
defaults:
  - data: mri.yaml
  - model: segmentation_module.yaml
  - callbacks: default.yaml
  - segmentation_module_model: unet.yaml
  - _self_

# Pytorch lightning trainer's argument
# Default flags are commented to avoid clustering the hyperparameters
trainer:
  accelerator: "gpu"
  # accumulate_grad_batches: 1
  # amp_backend: native
  # amp_level: O2
  # auto_lr_find: False
  # auto_scale_batch_size: False
  # auto_select_gpus: False
  # benchmark: True
  # check_val_every_n_epoch: 1
  # checkpoint_callback: True
  # default_root_dir:
  detect_anomaly: True
  # deterministic: False
  # fast_dev_run: False
  # flush_logs_every_n_steps: 100
  gpus: 1
  # gradient_clip_val: 0
  # limit_predict_batches: 1.0
  # limit_test_batches: 1.0
  # limit_train_batches: 1.0
  # limit_val_batches: 1.0
  # log_every_n_steps: 50
  # log_gpu_memory: False
  # logger: True
  max_epochs: 5
  # max_steps: None
  # min_epochs: None
  # min_steps: None
  # move_metrics_to_cpu: False
  # multiple_trainloader_mode: max_size_cycle
  # num_nodes: 1
  # num_processes: 1
  # num_sanity_val_steps: 2
  # overfit_batches: 0.0
  # plugins: None
  # precision: 16
  # prepare_data_per_node: True
  # process_position: 0
  # profiler: None
  # progress_bar_refresh_rate: None
  # reload_dataloaders_every_epoch: False
  # replace_sampler_ddp: True
  # resume_from_checkpoint: None
  # stochastic_weight_avg: False
  # sync_batchnorm: False
  # track_grad_norm: -1
  # truncated_bptt_steps: None
  # val_check_interval: 1.0
  # weights_save_path: None
  # weights_summary: top